### ISSUE TITLE
App not starting intermittently?

### ISSUE THREAD

**Issue by satmandu** [withinboredom/ipv6-wsl#1]
I can't seem to get the app to start after install. (It started once.)

Now when I double-click on `ipv6dup-ui.application` I get a little` Launching Application` window, and then nothing.

Any ideas on what I should try?

I have a bridge setup, and wsl2 is connecting through the bridge. I have the .wslconfig file with ipv6 enabled.

I see eth0 picking up ipv6 addresses too.

But I can not ping the wsl ipv6 address from another machine, nor can I ping an ipv6 machine...

Is there a config file I can edit to make sure the mac address of the interface is entered correctly for the app?

**Comment by withinboredom** [comment]
Is it in the icon tray on the lower right?

**Comment by satmandu** [comment]
There is no icon in the system tray.

**Comment by satmandu** [comment]
I think after uninstalling and hacking it out of the registry and reinstalling it is working now. :)

**Comment by withinboredom** [comment]
I can't think of anything that would make it crash. I may suggest deleting the config files in "C:\Users\[YOUR USER]\AppData\Local\Wicked_Monkey_Software\".

If it happens again, I'll do a special build with logging turned on so we can see why it happens.

**Comment by satmandu** [comment]
I did an install from the zip file, so maybe that was causing an error?

Also tried installing as admin, which might also have wreaked havoc. There's knowing too much sometimes... sigh.

**Comment by satmandu** [comment]
I did an install from the zip file, so maybe that was causing an error?

Also tried installing as admin, which might also have wreaked havoc. There's knowing too much sometimes... sigh.
